feign:
  client:
    config:
      default:
        loggerLevel: full
        requestInterceptors:
          - com.tuling.tulingmall.ordercurr.feignapi.interceptor.HeaderInterceptor
        readTimeout: 3000
        connectTimeout: 3000
mybatis:
  configuration:
    map-underscore-to-camel-case: true